[package]
name = "ppc"
version = "0.6.6"
authors = ["TropicSapling <tropical.productions.scratch@gmail.com>"]

[dependencies]
clap = "2.32.0"
term-painter = "0.2.4"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.5"